### ISSUE TITLE
page rendering issues

### ISSUE THREAD

**Issue by pklingem** [natew/obtvse#102]
see below:

using ref c544b794b660690cf92798ee8a839be25f406baa
### Firefox

![obtvse-stylesheet-issue-firefox](https://f.cloud.github.com/assets/46536/28567/0866721e-4c53-11e2-83b6-e19623b4bc83.png)
### Chromium

![obtvse-stylesheet-issue-chromium](https://f.cloud.github.com/assets/46536/28568/0e739c5e-4c53-11e2-9f56-fbeec2a1b6cc.png)

**Comment by stoplion** [comment]
same here

**Comment by natew** [comment]
Fixed by reverting, was an accidental merge.

**Comment by pklingem** [comment]
@natew did you push that?
