### ISSUE TITLE
Demo admin panel broken

### ISSUE THREAD

**Issue by iangcarroll** [natew/obtvse#103]
http://d.pr/i/tzcg

**Comment by natew** [comment]
This was broken a couple days ago for some reason the refresh branch was merged in.  Will reset it back asap.

## 

Nate Wienert
natewienert.com
@natebirdman

**Comment by syatnest** [comment]
just took a look. Last commit before the break was cd51854.

**Comment by natew** [comment]
Reset master branch, looks like I merged the refresh in by accident.
