### ISSUE TITLE
Problem with Gemfile?

### ISSUE THREAD

**Issue by Goles** [natew/obtvse#105]
I followed the instructions but I got:

```
#rails s
Gemfile syntax error:
/Users/user/Blog/obtvse/Gemfile:14: syntax error, unexpected ':', expecting $end
gem 'stringex', '~> 1', git: 'git://github.com/rsl/stringex.git'
```

Any clue?

**Comment by daylifemike** [comment]
change...
    git: 'git://github.com/rsl/stringex.git'
to...
    :git => 'git://github.com/rsl/stringex.git'

**Comment by natew** [comment]
No, upgrade to ruby 1.9

Nate
natewienert.com

**Comment by daylifemike** [comment]
I am running 1.9.  So is your Heroku demo (according to your notes) and it's not working either.  I pushed an untouched copy of your master to my own Heroku stack (running 1.9) and it didn't work until I made the above change.

**Comment by natew** [comment]
Nope, not the case.  Not sure why you're getting that error, but my demo was due to an old an incorrect merge I had done.  With the same line it is working now.
