### ISSUE TITLE
eventmachine 0.12.10 causes build error

### ISSUE THREAD

**Issue by dbc60** [natew/obtvse#106]
I'm building on Windows with Ruby 1.9.3p327. Running "bundle install" fails when it gets to eventmachine. I found that replacing "eventmachine (0.12.10) in Gemfile.lock with "eventmachine (1.0.0) gets around the issue.

**Comment by natew** [comment]
You'd want to update the Gemfile not Gemfile.lock, you're not supposed to touch that.  If you find one that works feel free to submit a pull request.
