### ISSUE TITLE
Rails Server Failure: NoMethodError in Posts#index

### ISSUE THREAD

**Issue by ghost** [natew/obtvse#124]
After firing up the rails server I get the following error:

NoMethodError in Posts#index

Showing /Users/distortpdx/Sites/obtvse/app/views/layouts/application.html.erb where line #6 raised:

undefined method `empty?' for nil:NilClass
  (in /Users/distortpdx/Sites/obtvse/app/assets/stylesheets/posts.css.scss)
Extracted source (around line #6):

3: <head>
4:   <title><%= html_title yield(:title) %></title>
5:   <%= csrf_meta_tag %>
6:   <%= stylesheet_link_tag 'application' %>
7:   <meta name="author" content="<%= CONFIG['name'] %>">
8:   <link href="/posts.rss" rel="alternate" title="RSS" type="application/rss+xml" />
9:   <link href='http://fonts.googleapis.com/css?family=Lato:300,900' rel='stylesheet' type='text/css' />

How can I fix this??? Thanks!

**Comment by ghost** [comment]
Fixed. Not sure what I did. Everything's working smoothly now.

**Comment by imgarylai** [comment]
I also got this problem.

Showing /Users/gary/Documents/works/obtvse/app/views/layouts/admin.html.erb where line #6 raised:

undefined method `empty?' for nil:NilClass
  (in /Users/gary/Documents/works/obtvse/app/assets/stylesheets/posts.css.scss)
Extracted source (around line #6):

3: <head>
4:   <title><%= html_title yield(:title) %></title>
5:   <%= csrf_meta_tag %>
6:   <%= stylesheet_link_tag 'application' %>
7:   <link href='http://fonts.googleapis.com/css?family=Lato:300,900' rel='stylesheet' type='text/css' />
8: </head>
9:
