### ISSUE TITLE
this app thoroughly doesn't work?

### ISSUE THREAD

**Issue by luckypoem** [natew/obtvse#129]
hi.
i installed ur app,but i visited http://as3.brite.biz:3007/,it shows error.how to fix it?

**Comment by natew** [comment]
I don't see anything at that url as of now, could you try running it in development mode and printing out the logs? 

Also obtvse2 is the latest version.

**Comment by luckypoem** [comment]
hi.
pls visit http://as3.brite.biz:3007/  , 
it shows:

NoMethodError in Posts#index

Showing /root/obtvse/app/views/layouts/application.html.erb where line #6 raised:

undefined method `empty?' for nil:NilClass
  (in /root/obtvse/app/assets/stylesheets/posts.css.scss)

Extracted source (around line #6):

3: <head>
4:   <title><%= html_title yield(:title) %></title>
5:   <%= csrf_meta_tag %>
6:   <%= stylesheet_link_tag 'application' %>
7:   <meta name="author" content="<%= CONFIG['name'] %>">
8:   <link href="/posts.rss" rel="alternate" title="RSS" type="application/rss+xml" />
9:   <link href='http://fonts.googleapis.com/css?family=Lato:300,900' rel='stylesheet' type='text/css' />

Rails.root: /root/obtvse
Application Trace | Framework Trace | Full Trace

app/views/layouts/application.html.erb:6:in `_app_views_layouts_application_html_erb___652378526__584403958'
app/controllers/posts_controller.rb:8:in`index'

Request

Parameters:

None

Show session dump

Show env dump
Response

Headers:

None
