### ISSUE TITLE
Obtvse's templete engine

### ISSUE THREAD

**Issue by krainboltgreene** [natew/obtvse#19]
Right now obtvse is using ERB. ERB is good for a while but there are a lot of other ways to generate HTML:
- HAML, requring less typing, clearner views, and encouraging the separation of parts (don't go 3 levels deep without partial-ling or generating in helpers), lots of people know and like HAML
- Slim, almost exactly the same reasons as HAML, except it requires even LESS typing, is faster (faster than ERB too), and has smart rendering (See http://slim-lang.org)

You've also got other helpers in the html generating field:
- Mab: Basically Markaby v2, but with blazing fast generation. Great for building small pockets of HTML in helpers, especially good at helping avoid if/case blocks in the view (which tend to take up 3-5 lines in ERB or haml)
- Handlebars: Good for pushing problems to the client side, lots of recent good news (Lots of good alternatives too)
- SAL: Hard to describe, but great for developing these types of applications. I suggest googling "github sal stonean". It's a mindblower.

Thoughts?

**Comment by alexcp** [comment]
I think it's really a matter of personal taste and ERB seems like a great default since it's standard html.

**Comment by krainboltgreene** [comment]
True, ERB is HTML with embedded ruby code. However, it's all down to HTML in the end. The difference is cost of work, maintain-ability, and ease of learning. Slim provides some easy shortcuts with the smart sectioning that reduces maint. costs.

Either way, some client side generation would be good to have.

**Comment by cobyism** [comment]
I would love this to all be done in HAML, but I know not everyone would agree.

ERB is simple because everyone knows it and can re-write the views in their own template language if they have a strong preference, but it depends how 'opinionated' this blogging platform is going to be. FWIW I think being opinionated about a certain way of doing things is important, so if it were my call I'd switch to HAML as early as possible.

**Comment by krainboltgreene** [comment]
I could do a PR to see how it'd look in each one. For the most part I can't imagine many people fuzzing with the views. Styles, yes, but views? Hmm. Maybe to add widgets and the like.

**Comment by natew** [comment]
My vote goes to ERB, only by a slight bit.  Personally I'd be interested in Slim, but as we can see here already everyone has a different taste and ERB has the least learning curve for the most people.

**Comment by krainboltgreene** [comment]
We could always have a slim branch. I'd be willing to maintain it. 

## 

Kurtis Rainbolt-Greene
The League Of Difference Engineers

**Comment by jakeonrails** [comment]
HAML or SLIM get my vote.

**Comment by matthelm** [comment]
My vote is for ERB. As per Issue #38 it's super important to keep the simplicity, so why use anything else?

**Comment by krainboltgreene** [comment]
I guess it depends on your definition of simplicity:

``` erb
<section id="post-<%= post.id %>">
  <div class="post contain">
    <%- if post.external? -%>
      <h1 class="external">
        <% if @single_post %><%= link_to post.title, post.url %><% else %><%= link_to post.title, post.url %><% end %>
        <%= link_to '⚓', post.slug, :class => 'permalink' %>
      </h1>
    <%- else -%>
      <h1><% if @single_post %><%= post.title %><% else %><%= link_to post.title, post.slug %><% end %></h1>
    <%- end -%>

    <% if post.content %><%= markdown(post.content).to_html.html_safe %><% end %>

    <%- if is_admin? -%>
      <ul class="actions">
        <li><%= link_to 'Edit', '/edit/' + post.id.to_s unless @preview %></li>
      </ul>
    <%- end -%>
  </div>

  <% if @single_post %><a class="button space-top" href="<%= root_url %>">Back to Blog</a><% end %>
</section>
```

``` slim
section id="post-#{post.id}"
  .post.contain
    - if post.external?
      h1.external
        - if @single_post
          = link_to post.title, post.url
        - else
          = link_to post.title, post.url
        = link_to '⚓', post.slug, class: 'permalink'
    - else
      h1
        - if @single_post
          = post.title
        - else
          = link_to post.title, post.slug
    = markdown(post.content).to_html.html_safe if post.content
    - if is_admin?
      ul.actions
        li = link_to 'Edit', '/edit/' + post.id.to_s unless @preview

  - if @single_post
    <a class="button space-top" href="<%= root_url %>">Back to Blog</a>
```

Of course it's a bit unfair, since writing in Slim helped me a few improvements:

``` slim
section id="post-#{post.id}"
  .post.container
    - post_header = @single_post ? post.title : link_to(post.title, post.slug)
    - if post.external?
      h1.external = post_header + ' ' + link_to('⚓', post.slug, class: 'permalink')
    - else
      h1 = post_header
    = markdown(post.content).to_html.html_safe if post.content
    - if is_admin?
      ul.actions
        li = link_to 'Edit', '/edit/' + post.id.to_s unless @preview
  = link_to "Back to Blog", root_path, class: 'button space-top' if @single_post
```

**Comment by matthelm** [comment]
I feel there is value in keeping the Gemfile as short as possible. Let's stick to basic Rails.

**Comment by natew** [comment]
I'd suport a branch with Slim if someone took the initiative.

**Comment by krainboltgreene** [comment]
I guess the question really is: Are we building a blog application **or** a clone of the svbtle platform?

If the former, then "keep the dependencies light" is a valid argument.

If the latter, then we should utilize as much power as we can.

**Comment by ghost** [comment]
I'd argue that most people using obtvse (and the 6 using svbtle) are familiar with ERB/Handlebars already and would be most comfortable with the master using ERB. Regardless, I don't mind experimenting so my vote goes towards Slim after seeing the above example. If obtvse is attempting to be a minimalistic blogging platform, Slim seems like a good fit.

**Comment by JulianGindi** [comment]
I completely understand the argument to stick with ERB but my vote would have to be for either HAML or Slim. True HTML is tedious to write and using an elegant templating language would allow for quicker coding. I also agree with the importance of the above question on whether this is meant to be a lightweight blogging engine or a copy of Svbtle. I can truly see this going either way...

**Comment by natew** [comment]
@krainboltgreene to answer your question we are building our own blog application, though I don't see how that argues against using a different template engine.

@bm1362 This is mostly my stance.  I think if we do go with slim, it is actually simple enough and well documented, so it shouldn't be a burden.

If someone is willing to convert it do get in touch with me first, I have been rewriting much of obtvse over the last few weeks so it would be worthwhile to start with the new code.

**Comment by JulianGindi** [comment]
@NateW Id be more than happy to get to work on converting the templates into Slim. It should not take to long. If anyone else wants to help that would make things go quicker obviously.

**Comment by natew** [comment]
Hmm... maybe I'll just push up this refresh branch soon then.  Need to blow my passwords out of it again and restore the obtvse theme so may be tomorrow or so.

**Comment by JulianGindi** [comment]
@NateW Alright. Sounds good to me.

**Comment by natew** [comment]
@Julian25 Check out refresh branch.

**Comment by JulianGindi** [comment]
Hey. I'll get to this ASAP. Just for clarification, we are going to convert things into Slim?

**Comment by natew** [comment]
Just want to update everyone since there are quite a few watching this thread, I've been working on a refresh branch that is pushed up here now.  It's a rethinking of obtvse with a new look and lots of cool stuff going on.

Would love some help to get it finished, but on that note as well if you're looking to convert templates to Slim I think it would probably be best to just do the refresh branch templates as we will transition to that eventually.
