### ISSUE TITLE
No scroll for content past screen height

### ISSUE THREAD

**Issue by hanchang** [natew/obtvse#27]
After I wrote a long blog post on the edit page (http://iamhanchang.herokuapp.com/edit/4 to be exact in this case), I realized that there is no scroll functionality for text that extends past the screen height... I can continue typing with no problem, but it just doesn't scroll and I can't see the text that I've typed.

This is on Mac OS X Lion (Macbook Pro 13" @ 1280x800) with the latest version of Chrome running on Heroku's Cedar platform.

I'll take a look at the issue myself, if I find a fix I'll certainly send a pull request. 

Lastly, thanks so much for Obtvse!!! I love it!

**Comment by hanchang** [comment]
Apparently the easy fix is to keep adding line breaks until the scrollbar shows. I'll do that for now and figure out the details later.

**Comment by natew** [comment]
Should be fixed in https://github.com/NateW/obtvse/commit/72cc359046bcb968c9a53b1908342f03e9d02aab
