### ISSUE TITLE
Preview isn't available for drafts

### ISSUE THREAD

**Issue by hanchang** [natew/obtvse#28]
Not a huge deal, but it would be nice to show previews for drafts that are not published yet.

Right now, if you preview a draft, it just displays a completely blank page.

**Comment by jkap** [comment]
You have to save the draft (but you don't have to publish it) and then it will preview.

I think the best way to get around this would be some sort of autosave, which is also being discussed in #26.

**Comment by jkap** [comment]
My mistake, while this was previously the case, it's not working anymore in d9829dda2a57ac6c6c4780b253c86a933288a65d.

**Comment by mduvall** [comment]
This was fixed in [#31](https://github.com/NateW/obtvse/pull/31). The Posts#show filter was removing drafts - the preview from the `/admin` page now works.

**Comment by mduvall** [comment]
The preview for drafts work as of [#34](https://github.com/NateW/obtvse/pull/34) for unsaved and updated blog posts.

**Comment by natew** [comment]
Should be fixed in latest version
