### ISSUE TITLE
Testing library

### ISSUE THREAD

**Issue by krainboltgreene** [natew/obtvse#33]
We've got three choices for testing libraries:
- RSpec: Often used, lots of support, great for dealing with complex applications
- TestUnit: DHH loves it, can be very terse, it's "just ruby" (Alt: Minitest)
- Cucumber: Easy to write behavior, can run through the js as well as the functionality (Alt: Spinach)

Then you've got factory libraries (I assume factories, but you could also do fixtures?)
- FactoryGirl: Recently updated to 3.0, oft used by the community
- Fabricator: Terser syntax, support for a multitude of ORMs, faster I think?
- Fixtures: :(

Finally we've also got to write tests with fake data, since this is a data (blog posts, comments, etc) app:
- Faker: Used by most
- Forgery: Terser syntax, slightly faster, better Lorem/"internet" data

Thoughts?

**Comment by jmorton** [comment]
When writing the first few tests my goal was verifying that the obvious ways of vandalizing content were prevented.

I started down the default TestUnit+Fixtures route but will run with RSpec a bit on my own branch over the next few days.  I have working familiarity with Cucumber too.  It would be good to hear from NateW before I go bumbling down a branch nobody wants to merge.

For what it's worth, I share your sentiment about fixtures.

**Comment by mindscratch** [comment]
I've preferred RSpec in the past but mini test also has its own "spec" thing which looks similar to rspec (although not as full featured).

**Comment by natew** [comment]
Closing this.... feel free anyone to write tests.  I'd prefer Rspec as well.
