### ISSUE TITLE
Easier Deployment

### ISSUE THREAD

**Issue by natew** [natew/obtvse#38]
We have Heroku, but the #1 issue people are having now is deployment.

We should
1. Collect the best guides for Rails deployment on a variety of platforms
2. Include capistrano examples
3. Set up a EC2 instance or VM image with Obtvse pre-configured?

**Comment by mduvall** [comment]
If Dalli is kept around there will need to be instructions on how to set up memcache with the host names and so on, from commit [1383a32014ee](https://github.com/NateW/obtvse/commit/1383a32014ee31ae43f99aaf6f82e9bff9e1581c#L0R7) it is a requirement. Static assets throw 500s when there is a cache miss and the memcache store is not configured correctly.

**Comment by natew** [comment]
It's been reverted as of now, but would appreciate if someone took the lead on this.

**Comment by FredericJacobs** [comment]
At [Evolucix](http://www.evolucix.com) we would like to offer a pilot program offering the ability to users to get started very quickly with a VMImage that we can propose to hosting customers.

**Comment by natew** [comment]
By all means, feel free to.

**Comment by mindscratch** [comment]
As for dealing with VM's, might be worth looking at [vagrant](http://rubygems.org/gems/vagrant).

**Comment by ghost** [comment]
I vagrant up that idea @mindscratch.
