### ISSUE TITLE
Argh. Tabs

### ISSUE THREAD

**Issue by EricR** [natew/obtvse#5]
The fact that you used tabs for indentation in seemingly random places in your codebase is, in my opinion, not okay. I know it sounds like a small thing, but it makes viewing and editing the code not pleasant. If each tab could be converted to two spaces, that would be great. Vim has a nice feature to do this painlessly (see http://vim.wikia.com/wiki/Converting_tabs_to_spaces).

Overall, cool project :-)

**Comment by natew** [comment]
Wow, really? Strange... I recently switched to Sublime perhaps thats why.  Will be fixed in next update.

**Comment by marksands** [comment]
Because, sometimes people are [caremad](http://caremad.com/).

**Comment by natew** [comment]
Sorry, didn't mean the wow, really? as being upset, more like "wow nate.. you really have tabs in there??".  I hate them too.
