### ISSUE TITLE
Seeing double scrollbars when creating and editing posts in Chrome

### ISSUE THREAD

**Issue by joshkerr** [natew/obtvse#51]
Two scroll bars appear on long posts when editing or creating them in the admin.

**Comment by matthelm** [comment]
Can you share a screenshot and some steps to reproduce the problem?

**Comment by natew** [comment]
I've seen it before and have it fixed on the branch I'm working on but I think it required a layout change and some CSS.  Unfortunately this branch is so far removed from master it would be worth just re-fixing separately.

**Comment by natew** [comment]
Fixed in upcoming version.

**Comment by natew** [comment]
Please check refresh branch
