### ISSUE TITLE
bundle install fails 

### ISSUE THREAD

**Issue by josephmisiti** [natew/obtvse#66]
using 

ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin10.0]

gem --version
1.8.23

bundle install fails with the following error on osx

Users/josephmisiti/mathandpencil/projects/blog/Gemfile:13:in `evaluate': compile error
/Users/josephmisiti/mathandpencil/projects/blog/Gemfile:13: syntax error, unexpected ':', expecting $end
gem 'stringex', '~> 1', git: 'git://github.com/rsl/stringex.git'
                            ^ (SyntaxError)
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/definition.rb:18:in`build'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler.rb:135:in `definition'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/cli.rb:220:in`install'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:in `send'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:in`run'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/vendor/thor.rb:263:in`dispatch'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/vendor/thor/base.rb:386:in `start'
       /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/bin/bundle:13
       /usr/bin/bundle:23:in`load'
       /usr/bin/bundle:23
There was an error in your Gemfile, and Bundler cannot continue.

**Comment by sstrudeau** [comment]
I'm guessing this is the Gemfile using a ruby 1.9.x syntax (: instead of =>) ... ruby-1.9.2 works for me. You might try changing the colons in the Gemfile to hashrockets and see if fixing the syntax helps, or switch to a newer version of ruby (I use rvm or rbenv to keep versions of ruby across projects manageable).

**Comment by josephmisiti** [comment]
If I could fix this issue by updating a gem/ruby or switching software, that would be ideal. I really want to use this as a blogging platform, but I am a python guy and do not know any ruby/rails stuff. I am not trying to avoid learning it, but really want I would love would just be deploy this platform on Heroku and get started with a blog if possible.

Thanks

**Comment by sstrudeau** [comment]
I just deployed the latest to heroku so I know it runs there. I believe the default heroku stack is on a version of ruby 1.9. RVM is probably the easiest way to get a project-specific version of ruby going: https://rvm.io/

**Comment by mindscratch** [comment]
I've also set it up locally and on heroku with ruby 1.9.2 and had no problems.

**Comment by natew** [comment]
Please upgrade to ruby 1.9
