### ISSUE TITLE
Published date

### ISSUE THREAD

**Issue by alexbaldwin** [natew/obtvse#69]
I started writing an article back in March and was trying to publish it today, but the published date is set to the date I created it. Functionality wise it makes sense to update the published date to the day I take off the "draft" flag. 

At least I should be able to change the date in settings and not have to muck with the database to do this kind of edit.

**Comment by natew** [comment]
This has been fixed in the upcoming release.

**Comment by alexbaldwin** [comment]
Thanks dude :) I'll wait to publish my old posts until then. Any word on an ETA?
