### ISSUE TITLE
Running on Mac OSX

### ISSUE THREAD

**Issue by amacgregor** [natew/obtvse#70]
I keep getting the following error:

rails s                                                                                                                                 

in /Volumes/Projects/obtvse
/Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require': no such file to load -- ripper (LoadError)
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/rails_best_practices-1.9.0/lib/rails_best_practices/core/runner.rb:3
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/rails_best_practices-1.9.0/lib/rails_best_practices/reviews/use_multipart_alternative_as_content_type_of_email_review.rb:2
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/rails_best_practices-1.9.0/lib/rails_best_practices/reviews.rb:24
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Library/Ruby/Gems/1.8/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in`require'
    from /Library/Ruby/Gems/1.8/gems/rails_best_practices-1.9.0/lib/rails_best_practices.rb:27
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in `require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in `each'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `each'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in`require'
    from /Library/Ruby/Gems/1.8/gems/bundler-1.1.3/lib/bundler.rb:119:in `require'
    from /Volumes/Projects/obtvse/config/application.rb:7
    from /Library/Ruby/Gems/1.8/gems/railties-3.2.0/lib/rails/commands.rb:53:in`require'
    from /Library/Ruby/Gems/1.8/gems/railties-3.2.0/lib/rails/commands.rb:53
    from /Library/Ruby/Gems/1.8/gems/railties-3.2.0/lib/rails/commands.rb:50:in `tap'
    from /Library/Ruby/Gems/1.8/gems/railties-3.2.0/lib/rails/commands.rb:50
    from script/rails:6:in`require'
    from script/rails:6

**Comment by alnjxn** [comment]
looks like missing dependency. try `gem install ripper`

**Comment by amacgregor** [comment]
I tried doing that and I'm still getting the same error.

**Comment by ghost** [comment]
Upgrade to Ruby 1.9.2, that will solve your problem.
