### ISSUE TITLE
Improper display of long post titles on admin index page of 'refresh' branch

### ISSUE THREAD

**Issue by cobyism** [natew/obtvse#79]
For posts with a long title, the text in the admin index page overflows over the top of any subsequent post titles. Here's a screenshot:

![post title problem](http://f.cl.ly/items/3d2Z3T2V2A031E3u1020/admin-lineheight-issue-1.jpg)

In the above image, the second post in the sequence is the one with the really long name, and it's the third post that is called "Title link". I'm thinking this is probably just a whitespace wrapping attribute or a forced attribute height somewhere the doesn't account for overflow.

It's clearly not a problem many people will have, but I thought it was worth bringing up. I'd look into it myself but I'm just about to start into a new job and don't have time to look at it just now.

BTW the work you've done on the refresh branch looks fantastic! I love that new LHS sidebar in the post edit screen—it was a little hard to find where I had to go to save changes to a post (the bottom right circle thing wasn't immediately obvious), but I really do like the direction you're going in!

**Comment by natew** [comment]
FIxed in newer versions.
