### ISSUE TITLE
Security issues...

### ISSUE THREAD

**Issue by ndreckshage** [natew/obtvse#92]
I think the simple http authentication should be replaced with a more secure system -- possibly authlogic https://github.com/binarylogic/authlogic/

additionally, example.html/admin is the number is the number 1 place someone would try and crack. maybe instead of /admin it could be /login as defined in config.yml

I'll work on incorporating this into a fork, but just wanted to mention it as issue...

**Comment by lenaschoenburg** [comment]
If I find the time, I want to add authentication and authorization support with devise.

**Comment by ndreckshage** [comment]
added devise https://github.com/NateW/obtvse/pull/94
